#!/usr/bin/python
# -*- coding: iso-8859-15 -*-

# CD-Crisol v. 0.1 (https://forja.rediris.es/projects/cd-crisol)
# Devel by: David Barragán Merino (d.barragan.alumnos.uc3m.es)
# CRISOL-UC3M (http://crisol.uc3m.es)

import os
os.chdir("/usr/share/cd-crisol/")
import sys
import shutil
import cdcrisollib

MASTER_DIR = "/usr/share/cd-crisol"
CONFIG_DIR = os.getenv("HOME")+"/.cd-crisol"
# DTD's
CATEGORIES_DTD = MASTER_DIR + "/categories.dtd"
APPS_DTD = MASTER_DIR + "/apps.dtd"
INCLUDES_DTD = MASTER_DIR + "/includes.dtd"
# System's XML files
MASTER_CATEGORIES_XML = MASTER_DIR + "/categories.xml"
MASTER_APPS_XML = MASTER_DIR + "/apps.xml"
# User's XML files
USER_CATEGORIES_XML = CONFIG_DIR + "/categories.xml"
USER_APPS_XML = CONFIG_DIR + "/apps.xml"
USER_INCLUDES_XML = CONFIG_DIR + "/includes.xml"
# User's config variables
IMAGE_DIR = CONFIG_DIR + "/image"
SOFTWARE_DIR = CONFIG_DIR + "/software"
ICONS_DIR = CONFIG_DIR + "/icons"
TEMPLATE_DIR = MASTER_DIR+"/baseconfig/templates/default" 
ISO_FILE = CONFIG_DIR + "/CD-Crisol.iso"
HTML_DIR = IMAGE_DIR + "/html"


if not os.path.exists(CONFIG_DIR):
	os.mkdir(CONFIG_DIR)
	shutil.copy(MASTER_DIR+"/baseconfig/config",CONFIG_DIR+"/config")
	shutil.copy(MASTER_DIR+"/baseconfig/categories.xml",CONFIG_DIR+"/categories.xml")
	shutil.copy(MASTER_DIR+"/baseconfig/apps.xml",CONFIG_DIR+"/apps.xml")
	shutil.copy(MASTER_DIR+"/baseconfig/includes.xml",CONFIG_DIR+"/includes.xml")

if os.path.exists(CONFIG_DIR+"/config"): 
	execfile(CONFIG_DIR+"/config")


class CDCrisol:
	def __init__(self, xml_files, dtd_files):
		self.__xml_files = []
		self.__xml_files = xml_files
		self.__dtd_files = []
		self.__dtd_files = dtd_files
		self.__image = cdcrisollib.Image(self.__xml_files, self.__dtd_files)

	def html(self,image_dir,template_dir):
		if not os.path.exists( image_dir ): 
			os.mkdir( image_dir )
                if not os.path.exists( image_dir + "/html" ): 
			os.mkdir( image_dir + "/html" )
		else:
			os.system( "rm -rf '" + image_dir + "/html"  + "'" )
			os.mkdir( image_dir+"/html" )

		self.__image.gen_html(image_dir+"/html", template_dir )
	
	def list(self):
		for category in self.__image.get_all_categories():
        		if category.is_included(): 
				print "\t+ " + category.get_name() +" (" + category.get_label() + ")" 
                        elif not category.is_included(): 
				print "\t- " + category.get_name() +" (" + category.get_label() + ")"
			for app in self.__image.get_apps_by_category( category.get_label() ):
        	        	if app.is_included(): 
					print "\t  + " + app.get_name()
                        	elif not app.is_included():
					print "\t  - " + app.get_name()
	def add_category(self):
	        print "Write the \"Category Name\":",
                name = raw_input()
                print "Write the \"Category Label\":",
                label = raw_input()
                if ( self.__image.add_category( [name, label] )):
			print "!! Adding \"" + name + "\" category." 
			self.__image.save_categories_to_xml_file()
		else:
			print "EE Imposible add this new category, it's posible that there is another one with te same label."

	def del_category(self, label = ""):
		if self.__image.del_category(label):
			print "!! Deleting category \"" + label + "\""
			self.__image.save_categories_to_xml_file()
			self.__image.save_includes_to_xml_file()
		else:
			print "EE Imposible delete the category. It's posible that there isn't any category with this label or this category is protected"
		

	def modify_category(self, label):
		if self.__image.get_category_by_label(label) == None:
			print "EE There isn't any category with this label"
		else:
			dict = self.__image.get_category_dict_by_label(label)
			values = []
			print "Write the \"Category Name\" (default: \"" + dict['name'] + "\"):",
			name = raw_input()
			if name == "": name = dict['name']
			values.append(name)
			if self.__image.modify_category_values(label, values):
				print "!! Modify \"" + name + "\" category." 
				self.__image.save_categories_to_xml_file()
				self.__image.save_applications_to_xml_file()
			else: 
				print "EE There aren't tow o more categories with the same label."

	def select_category(self, label):
		if self.__image.select_category(label):
			print "!! The category is selected"
			self.__image.save_includes_to_xml_file()
		else:
			print "EE There isn't any category with this label"
			
	def unselect_category(self, label):
		if self.__image.unselect_category(label):
			print "!! The category is unselected"
			self.__image.save_includes_to_xml_file()
		else:
			print "EE There isn't any category with this label"
	
	def view_category(self, label):
		if self.__image.get_category_by_label(label) == None:
			print "EE There isn't any category with this label"
		else:
			dict = self.__image.get_category_dict_by_label(label)
			print " CATEGORY DETAILS:"
			print ""
			print "   NAME:\t\t" + dict['name']
			print "   LABEL:\t\t" + dict['label']
			if dict["included"]: print "   INCLUDED:\t\tyes"
			else: print "   INCLUDED:\t\tno"
			if len( dict['apps'] ) > 0:
				print "   APLICATIONS:"
				for app in dict['apps']:
					print "         \t\t" + app['name']
			print""

	def add_application(self):
		print "Name:",
                name = raw_input()
		print "Version:",
		version = raw_input()
                print "Site:",
                site = raw_input()
                print "Manual (press ENTER to ignore):",
                manual = raw_input()
                print "Description:",
                description = raw_input()
                print "File:",
                file = raw_input()
                print "Software URL:",
                software_url = raw_input()
                print "Icon:",
                icon = raw_input()
                print "Icono URL (press ENTER to ignore):",
                icon_url = raw_input()
                print "MD5Sum:",
                md5sum = raw_input()
                categories = []
                category = None
                while category != "":
                        if category != None:
                                categories.append(category)
                        print "Categories (press ENTER to finish):",
                        category = raw_input()
                alternatives = []
                alt = None
                while alt != "":
                        if alt != None:
                                alternatives.append(alt)
                        print "Alternatives (press ENTER to finish):",
                        alt = raw_input()
                self.__image.add_app( [name, version, site, manual, description, file, software_url, icon, icon_url, md5sum, categories, alternatives ] )
                self.__image.save_applications_to_xml_file()

	def del_application(self, naem):
		if self.__image.del_app(name):
			print "!! Deleting application \"" + name + "\""
			self.__image.save_applications_to_xml_file()
			self.__image.save_includes_to_xml_file()
		else:
			print "EE Imposible delete the application. It's posible that there isn't any application with this name or this application is protected"
	
	def modify_application(self, name):
		if self.__image.get_app_by_name(name) == None:
			print "EE There isn't any category with this label"
		else:
			dict = self.__image.get_app_dict_by_name(name)
			values = []

			print "Write the \"App Version\" (default: \"" + dict['version'] + "\"):",
			version = raw_input()
			if version == "": version = dict['version']
			values.append(version)

			print "Write the \"App Site\" (default: \"" + dict['site'] + "\"):",
			site = raw_input()
			if site == "": site = dict['site']
			values.append(site)

			if dict['manual'] == None:	
				print "Write the \"App Manual page\" (default: \"\"):",
				manual = raw_input()
			else:
				print "Write the \"App Manual page\" (default: \"" + dict['manual'] + "\"):",
				manual = raw_input()
				if manual == "": manual = dict['manual']
			values.append(manual)

			print "Write the \"App Description\" (default: \"" + dict['description'] + "\"):",
			description = raw_input()
			if description == "": description = dict['description']
			values.append(description)

			print "Write the \"App File\" (default: \"" + dict['file'] + "\"):",
			file = raw_input()
			if file == "": file = dict['file']
			values.append(file)

			print "Write the \"App Software URL\" (default: \"" + dict['software_url'] + "\"):",
			software_url = raw_input()
			if software_url == "": software_url = dict['software_url']
			values.append(software_url)
			
			print "Write the \"App Icon\" (default: \"" + dict['icon'] + "\"):",
			icon = raw_input()
			if icon == "": icon = dict['icon']
			values.append(icon)

			if dict['icon_url'] == None:
					print "Write the \"App Icon URL\" (default: \"\"):",
					icon_url = raw_input()
			else:
				print "Write the \"App Icon URL\" (default: \"" + dict['icon_url'] + "\"):",
				icon_url = raw_input()
				if icon_url == "": icon_url = dict['icon_url']
			values.append(icon_url)

			print "Write the \"App MD5Sum\" (default: \"" + dict['md5sum'] + "\"):",
			md5sum = raw_input()
			if md5sum == "": md5sum = dict['md5sum']
			values.append(md5sum)

			c = ""
			for ctg in dict['categories']:
				if ctg != None: 
					c =  c + ", " + ctg 
			print "Write \"default\" to get the defaults \"App Categories\" or press ENTER to add the news ones (default: \"" + c + "\"):",
			cat = raw_input()
			categories = []
			if cat == "default": 
				categories = dict['categories']
			else:
				cat = "-"
				while cat != "":
					print "Categories (press ENTER to finish):"
					cat = raw_input()
					if cat != "":
                          	      		categories.append(cat)
			values.append(categories)

			a = ""
			for atn in dict['alternatives']:
				if atn != None: 
					a = a + ", " + atn 
			print "Write the \"App Alternatives\" (default: \"" + a + "\"):",
			alt = raw_input()
			alternatives = []
			if alt == "": 
				alternatives = dict['alternatives']
			else:
				while alt != "":
					if alt != None:
                          	      		alternatives.append(alt)
					print "Alternatives (press ENTER to finish):",
					alt = raw_input()
			values.append(alternatives)

			if self.__image.modify_app_values(name, values):
				print "!! Modify \"" + name + "\" application." 
				self.__image.save_applications_to_xml_file()
			else: 
				print "EE There aren't tow o more applications with the same name."

	def select_application(self, name):
		if self.__image.select_app(name):
			print "!! The application is selected"
			self.__image.save_includes_to_xml_file()
		else:
			print "EE There isn't any application with this name"

	def unselect_application(self, name):
		if self.__image.unselect_app(name):
                        print "!! The application is unselected"
                        self.__image.save_includes_to_xml_file()
                else:
                        print "EE There isn't any application with this name"

	def view_application(self, name):	
		if self.__image.get_app_by_name(name) == None:
			print "EE There isn't any application with this name"
		else:
			dict = self.__image.get_app_dict_by_name(name)
			print " APPLICATION DETAILS:"
			print ""
			print "   NAME:\t\t" + dict['name']
			print "   VERSION:\t\t" + dict['version']
			
			print "   SITE:\t\t" + dict['site']
			if dict['manual'] != None: print "   MANUAL:\t\t" + dict['manual']
			print "   FILE:\t\t" + dict['name']
			print "   SOFTWARE URL:\t" + dict['software_url']
			print "   ICON:\t\t" + dict['icon']
			if dict['icon_url'] != None:print "   ICON URL:\t\t" + dict['icon_url']
			print "   MD5SUM:\t\t" + dict['md5sum']
			if dict['included']: print "   INCLUDED:\t\tyes"
			else: print "   INCLUDED:\t\tno"
			if len( dict['categories'] ) > 0:
				print "   CATEGORIES:"
				for cat in dict['categories']:
					print "         \t\t" + cat	
			if len( dict['alternatives'] ) > 0:
				print "   ALTERNATIVES:"
				for alt in dict['alternatives']:
					if alt != None:
						print "         \t\t" + alt
			print "   DESCRIPTION:\t\t" + dict['description']
			print""

        def clean(self, image_dir):
                os.system( "rm -rf '"+ image_dir +"'" )

        def mrproper(self, config_dir):
                os.system( "rm -rf '"+ config_dir +"'" )
	
	def iso(self, image_dir, iso_file):
		self.__image.make_iso( image_dir, iso_file )

	def download(self, software_dir, icon_dir):
		if not os.path.exists( software_dir ): os.mkdir( software_dir )
		if not os.path.exists( icon_dir ): os.mkdir( icon_dir )
		for category in self.__image.get_all_categories():
			if category.is_included():
				for app in category.get_all_apps():
					if app.is_included() :
						app.download_software( software_dir )
						app.download_icon( icon_dir )

	def copy( self, image_dir, software_dir, icons_dir, master_dir ):
		if not os.path.exists( image_dir ): os.mkdir( image_dir )
		if not os.path.exists( image_dir + "/software" ): os.mkdir(image_dir + "/software" )
		if not os.path.exists( image_dir + "/html" ): os.mkdir(image_dir + "/html" )
		if not os.path.exists( image_dir + "/html/icons" ): os.mkdir( image_dir + "/html/icons" )
		for category in self.__image.get_all_categories():
			if category.is_included():
				for app in category.get_all_apps():
					if app.is_included():
						if not os.path.exists( image_dir + "/software/" + app.get_file_name() ):
							os.symlink( software_dir + "/" + app.get_file_name(),image_dir + "/software/" + app.get_file_name() )
						if os.path.exists( icons_dir + "/" + app.get_icon_name() ):
							os.symlink( icons_dir + "/" + app.get_icon_name(),image_dir + "/html/icons/" + app.get_icon_name() )
		if not os.path.exists( image_dir + "/autorun.inf" ): os.symlink( master_dir + "/cd-base/autorun.inf", image_dir + "/autorun.inf" )
		if not os.path.exists( image_dir + "/browsercall.exe" ): os.symlink( master_dir + "/cd-base/browsercall.exe", image_dir + "/browsercall.exe" )
		if not os.path.exists( image_dir + "/logo.ico" ):os.symlink( master_dir + "/cd-base/logo.ico", image_dir + "/logo.ico" )



"""------------------------------------"""
def print_help():
	print "Usage: " + sys.argv[0] + " <option> [parameter]\n"
	print "Options:"
	print ""
	print "  Aplications manipulations:"
	print "    add_app\t\t\t  Add an application."
	print "    del_app <app-name>\t\t  Remove an application."
	print "    mod_app <app-name>\t\t  Modify an application."
	print "    select_app <app-name>\t  Select applications to include."
	print "    unselect_app <app-name>\t  Unselect applications to include."
	print "    view_app <app-name>\t\t  View an application details"
	print ""
	print "  Categories manipulations:"
	print "    add_categ\t\t\t  Add a category."
	print "    del_categ <categ-label>\t  Remove a category."
	print "    mod_categ <categ-label>\t  Modify a category"
	print "    select_categ <categ-label>\t  Select categories to include."
	print "    unselect_categ <categ-label>  Unselect categories to include."
	print "    view_categ <categ-label>\t  View a category details"
	print ""
	print "  Image options:"	
	print "    all\t\t\t\t  Execute html, copy and iso actions."
	print "    clean\t\t\t  Clean the image directory."
	print "    copy\t\t\t  Copy base files, software and icons."
	print "    download\t\t\t  Download the necesary software."
	print "    html\t\t\t  Generate html files into the image."
	print "    iso\t\t\t\t  Generate an iso image from image directory."
	print "    list\t\t\t  List all aplications and the status."
	print "    mrproper\t\t\tClean the user config dir."
	print ""

if len( sys.argv ) < 2 or len ( sys.argv ) > 3:
	print_help()
else:
	
	xml_files = [ MASTER_CATEGORIES_XML, MASTER_APPS_XML, USER_CATEGORIES_XML, USER_APPS_XML, USER_INCLUDES_XML ]
	dtd_files = [ CATEGORIES_DTD, APPS_DTD, INCLUDES_DTD]

	try:
		cdcrisol = CDCrisol( xml_files, dtd_files )
	except Exception:	
		print"EE Error. the program finish."
	
	if sys.argv[1] == "html":
		cdcrisol.html( IMAGE_DIR, TEMPLATE_DIR )
        elif sys.argv[1] == "clean":
		cdcrisol.clean(IMAGE_DIR)
	elif sys.argv[1] == "mrproper":
		cdcrisol.view_mrproper()
	elif sys.argv[1] == "iso":
		cdcrisol.iso(IMAGE_DIR, ISO_FILE)
	elif sys.argv[1] == "download":
		cdcrisol.download(SOFTWARE_DIR, ICONS_DIR)
	elif sys.argv[1] == "copy":
		cdcrisol.copy(IMAGE_DIR,SOFTWARE_DIR,ICONS_DIR,MASTER_DIR)
	elif sys.argv[1] == "all":
		cdcrisol.html(IMAGE_DIR,TEMPLATE_DIR)
		cdcrisol.copy(IMAGE_DIR,SOFTWARE_DIR,ICONS_DIR,MASTER_DIR)
		cdcrisol.iso(IMAGE_DIR,ISO_FILE)
	elif sys.argv[1] == "list":
		cdcrisol.list()
	# Categories functions
	elif sys.argv[1] == "add_categ":
		cdcrisol.add_category()
	elif sys.argv[1] == "del_categ":
		cdcrisol.del_category(sys.argv[2])
	elif sys.argv[1] == "mod_categ":
		cdcrisol.modify_category(sys.argv[2])
	elif sys.argv[1] == "select_categ":
		cdcrisol.select_category(sys.argv[2])
	elif sys.argv[1] == "unselect_categ":
		cdcrisol.unselect_category(sys.argv[2])
	elif sys.argv[1] == "view_categ":
		cdcrisol.view_category(sys.argv[2])
	# Applications fuction
	elif sys.argv[1] == "add_app":
		cdcrisol.add_application()
	elif sys.argv[1] == "del_app":
		cdcrisol.del_application(sys.argv[2])
	elif sys.argv[1] == "mod_app":
		cdcrisol.modify_application(sys.argv[2])
	elif sys.argv[1] == "select_app":
		cdcrisol.select_application(sys.argv[2])
	elif sys.argv[1] == "unselect_app":
		cdcrisol.unselect_application(sys.argv[2])
	elif sys.argv[1] == "view_app":
		cdcrisol.view_application(sys.argv[2])
	else:
		print_help()

